const sportsList = [
	"Alpine Skiing",
	"Archery",
	"Arm Wrestling",
	"Australian Boxing",
	"Auto Racing",
	"Badminton",
	"Barrel Racing",
	"Base Jumping",
	"Baseball",
	"Basketball",
	"Beach Volleyball",
	"Bocce Ball",
	"Body Building",
	"Bowling",
	"Boxing",
	"Canoeing",
	"Cheerleading",
	"Chess",
	"Chess",
	"Clay Pigeon Shooting",
	"Climbing",
	"Cricket",
	"Cross Country Running",
	"Cross Country Skiing",
	"CrossFit",
	"Crouquet",
	"Curling",
	"Darts",
	"Deadlifting",
	"Demolition Derby",
	"Disc Golf",
	"Discus",
	"Disk Golf",
	"Diving",
	"Dodgeball",
	"Dog Sledding",
	"Downhil Mountain Biking",
	"Downhill Skiing",
	"Drag Racing",
	"Drone Racing",
	"Fencing",
	"Field Hockey",
	"Figure Skating",
	"Fishing",
	"Fooseball",
	"Football",
	"Formula Racing",
	"Gliding",
	"Golf",
	"Gymnastics",
	"Hackysac",
	"Hang gliding",
	"Horseshoes",
	"Hot Air Balloning",
	"Hunting",
	"Hurdles",
	"Hydroplane Racing",
	"ice Hockey",
	"Ice Yachting",
	"inline Skating",
	"Inline Speed Skating",
	"Jai Alai",
	"Javelin",
	"Jet Skiing",
	"Jiu-Jitsu",
	"Jogging",
	"Jokgu",
	"Judo",
	"Karate",
	"Kart Racing",
	"Kayaking",
	"Kegel",
	"Kickball",
	"Kickboxing",
	"Kite Boarding",
	"Kite Fighting",
	"Kite Surfing",
	"Kung Fu",
	"Lacrosse",
	"Land Sailing",
	"Laser Tag",
	"Lawn Mower Racing",
	"Log Rolling",
	"Long Jump",
	"Longboarding",
	"Luge",
	"Lumberjack",
	"Marathon",
	"Miniature Golf",
	"Mixed Martial Arts",
	"Mogul Skiing",
	"Motocross",
	"Motorcycle Speedway",
	"Motorcycling",
	"Mountain Biking",
	"Mountaineering",
	"Off Road Racing",
	"Paddle Tennis",
	"Paintball",
	"Parachuting",
	"Parallel Bars",
	"Ping Pong",
	"Poker",
	"Pole Vaulting",
	"Polo",
	"Pool",
	"Power Boat Racing",
	"Powerlifting",
	"Race Walking",
	"Racquetball",
	"Rafting",
	"Reining",
	"Ringball",
	"Rodeo",
	"Roller Blading",
	"Roller Hockey",
	"Rolller Skating",
	"Rowing",
	"Rugby",
	"Running",
	"Sailing",
	"Scuba Diving",
	"Shot put",
	"Show Jumping",
	"Shuffleboard",
	"Skateboarding",
	"Ski Jumping",
	"Skiing -Cross Country",
	"Skiing -Downhill",
	"Skydiving",
	"Slalom Skiing",
	"Snowboarding",
	"Snowkiting",
	"Snowmobile Racing",
	"Snowshoeing",
	"Soccer",
	"Softballl",
	"Speed Skating",
	"Sport Car Racing",
	"Sport Fishing",
	"Squash",
	"Sumo Wrestling",
	"Super Giant Slalom",
	"Surfing",
	"Synchronized Swimming",
	"Taekwondo",
	"Tamburello",
	"Target Shooting",
	"Tee Ball",
	"Telemark Skiing",
	"Tennis",
	"Tetherball",
	"Touch Football",
	"Tractor Pulling",
	"Trampolining",
	"Triathelete",
	"Ultimate",
	"Uneven Bars",
	"Volleyball",
	"Wakeboarding",
	"Water Polo",
	"Weightlifting",
	"Wheelchair Basketball",
	"Wiffleball",
	"Windsurfing",
	"Wrestling",
];
function getSportsList() {
	return sportsList;
}

const skillList = ["Advanced", "Expert", "Pro"];
function getSkillList() {
	return skillList;
}

const studentExperienceList = ["Beginner", "Intermediate", "Advanced"];
function getStudentExperienceList() {
	return studentExperienceList;
}

const timeList = [
	"1:00am",
	"1:30am",
	"2:00am",
	"2:30am",
	"3:00am",
	"3:30am",
	"4:00am",
	"4:30am",
	"5:00am",
	"5:30am",
	"6:00am",
	"6:30am",
	"7:00am",
	"7:30am",
	"8:00am",
	"8:30am",
	"9:00am",
	"9:30am",
	"10:00am",
	"10:30am",
	"11:00am",
	"11:30am",
	"12:00pm",
	"12:30pm",
	"1:00pm",
	"1:30pm",
	"2:00pm",
	"2:30pm",
	"3:00pm",
	"3:30pm",
	"4:00pm",
	"4:30pm",
	"5:00pm",
	"5:30pm",
	"6:00pm",
	"6:30pm",
	"7:00pm",
	"7:30pm",
	"8:00pm",
	"8:30pm",
	"9:00pm",
	"9:30pm",
	"10:00pm",
	"10:30pm",
	"11:00pm",
	"11:30pm",
	"12:00am",
	"12:30am",
];
function getTimeList() {
	return timeList;
}
